server:
  port: 8085

spring:
  application:
    name: recharge-service

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE   # ✅ FIXED
    driverClassName: oracle.jdbc.OracleDriver
    username: scott
    password: DEVI

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000